name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Create Folder
        run: mkdir myapp

      - name: Build
        run: go build -o myapp ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: myapp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Deploy to Raspberry Pi
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ vars.SSH_PORT || '22' }}
        run: |
          echo "$SSH_KEY" > ~/.ssh/private_key && chmod 600 ~/.ssh/private_key
          ls -l
          scp -P $SSH_PORT -i ~/.ssh/private_key api $SSH_USER@$SSH_HOST:/home/$SSH_USER/api
          ssh -p $SSH_PORT -i ~/.ssh/private_key $SSH_USER@$SSH_HOST "chmod +x /home/$SSH_USER/api && sudo systemctl restart goapi.service"
